name: Manual PyInstaller Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # This means run the build on an Ubuntu Linux server

    steps:
      - name: Check out your code
        uses: actions/checkout@v3  # This fetches your repo’s latest code

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use Python 3.11

      - name: Install PyInstaller
        run: pip install pyinstaller  # Installs PyInstaller on the runner
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements  # Install your project dependencies
          
      - name: Build your executable
        run: pyinstaller --onefile Epoch/__main__.py --name Epoch

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Epoch
          path: dist/Epoch
